### ISSUE TITLE
Moodle 3.9 behat test failure

### ISSUE THREAD

**Issue by aspark21** [open-lms-open-source/moodle-mod_collaborate#12]
Moodle 3.9.0
Collaborate:master@d917766 

Moodle exception: Exception - Warning: count(): Parameter must be an array or an object that implements Countable in [dirroot]/mod/collaborate/classes/renderables/meetingstatus.php on line 131 More information about this error
        
        Exception - Warning: count(): Parameter must be an array or an object that implements Countable in [dirroot]/mod/collaborate/classes/renderables/meetingstatus.php on line 131
        More information about this error
        
        
            
        ×
            
        Debug info: 
         
        Error code: generalexceptionmessage
         (Exception)
https://github.com/blackboard-open-source/moodle-mod_collaborate/blob/master/classes/renderables/meetingstatus.php#L131-L133

**Comment by jrchamp** [comment]
It's probably `null`. It's weird that this `if` block is outside of the "are we using groups?" `if` block immediately above it. It means both values will always be null if not using groups.

**Comment by aspark21** [comment]
Confirmed as fixed in latest master
